module Posts
  url_prefix = "http://res.cloudinary.com/dkympkwdz/image/upload/ar_3,c_fill,g_auto,h_700,q_80,w_700/f_jpg/"
  DATA = [
    { title: "Crate & Barrel Braiden Coffee Table", description: "Excellent condition, we bought another style coffee table, so selling it.  Local pick up. Cash only.",
      img_url1: "#{url_prefix}/1.jpg", img_url2: "#{url_prefix}/2.jpg", img_url3: "#{url_prefix}/3.jpg" },
    { title: "Great coffee table", description: "I am selling a great coffee table. Very sturdy and solid beautiful wood. I am moving and trying to downsize.",
      img_url1: "#{url_prefix}/4.jpg", img_url2: nil, img_url3: nil },
    { title: "LEATHER OFFICE CHAIR FOR SALE!", description: "LEATHER OFFICE CHAIR FOR SALE! EXCELLENT CONDITION!",
      img_url1: "#{url_prefix}/7.jpg", img_url2: "#{url_prefix}/8.jpg", img_url3: nil },
    { title: "New Soup Pot & Steamer 4 QT. Stainless Steel", description: "4 quart stainless steel pot, great for cooking. Beautiful shiny design, satisfaction guaranteed.",
      img_url1: "#{url_prefix}/10.jpg", img_url2: nil, img_url3: nil },
    { title: "WINE BARREL HAMMOCK", description: "Repurposed Wine Barrel made into a BEAUTIFUL HAMMOCK. Attached to a very attractive sturdy metal frame.",
      img_url1: "#{url_prefix}/13.jpg", img_url2: "#{url_prefix}/14.jpg", img_url3: "#{url_prefix}/15.jpg" },
    { title: "Asian-themed decorative tray", description: "Asian-themed decorative tray. Made in Vietnam. 12\" x 12\". Two handles.",
      img_url1: "#{url_prefix}/16.jpg", img_url2: nil, img_url3: nil },
    { title: "Electrolux Ergorapido Lithium Ion Plus 2-in-1", description: "Features o Swivel Steering Twists and turns around your corners and furniture with ease. o Energy Star",
      img_url1: "#{url_prefix}/19.jpg", img_url2: nil, img_url3: nil },
    { title: "Large Satin Pillow Set and 3 Big Cusion Covers, New", description: "Luxurious set of 2 pillows in padded satin, one measures 13\"L x 19\"W, the other measures 15\"L x 15\"W.",
      img_url1: "#{url_prefix}/22.jpg", img_url2: "#{url_prefix}/23.jpg", img_url3: "#{url_prefix}/24.jpg" },
    { title: "4 - \"NEW 10 Pieces Hang It Up Tool Kit For Women", description: "10 Pieces Hang It Up Tool Kit For Woman by Barbara K Features: 10 ft. tape to measure accurately",
      img_url1: "#{url_prefix}/25.jpg", img_url2: "#{url_prefix}/26.jpg", img_url3: nil },
    { title: "Cuisinart ICE-21 Yogurt-Ice Cream Maker", description: "Used it a few time and haven't used it since been in storage and now need to clean it out.",
      img_url1: "#{url_prefix}/28.jpg", img_url2: "#{url_prefix}/29.jpg", img_url3: nil },
    { title: "Rachael Ray Kitchen Shear and Paring Knife (NEW)", description: "Rachael Ray Kitchen Shear and Pairing Knife, New in sealed blister pack.",
      img_url1: "#{url_prefix}/31.jpg", img_url2: nil, img_url3: nil },
    { title: "Brand new Circulon Genesis Hard-Anodized", description: "Rachael Ray Kitchen Shear and Pairing Knife, New in sealed blister pack.",
      img_url1: "#{url_prefix}/34.jpg", img_url2: "#{url_prefix}/35.jpg", img_url3: nil },
    { title: "Kirby Classic 3", description: "Kirby Classic 3 with attachments. Single Owner and in good working condition.",
      img_url1: "#{url_prefix}/37.jpg", img_url2: "#{url_prefix}/38.jpg", img_url3: "#{url_prefix}/39.jpg" },
    { title: "Scale", description: "Taylor brand scale, manual, no need for battery. Easy to use and light weight. 10.5\"L x 9.5\"W x 1.5\"H",
      img_url1: "#{url_prefix}/40.jpg", img_url2: "#{url_prefix}/41.jpg", img_url3: "#{url_prefix}/42.jpg" },
    { title: "Lazy Susan", description: "20 inch Lazy Susan used once.",
      img_url1: "#{url_prefix}/43.jpg", img_url2: nil, img_url3: nil },
    { title: "Various Crystal Glasses", description: "Different size crystalwares with bamboo engrave.",
      img_url1: "#{url_prefix}/46.jpg", img_url2: "#{url_prefix}/47.jpg", img_url3: "#{url_prefix}/48.jpg" },
    { title: "Tech 21 Note 5 Phone Case", description: "Call or text only...",
      img_url1: "#{url_prefix}/49.jpg", img_url2: nil, img_url3: nil },
    { title: "**RARELY USED** Samsung Galaxy S7 Edge Verizon", description: "Verizon. Unlocked. Includes: original accessories and box; Zagg HD screen protector, 1x unused clear case, and 1x used Spigen smoke colored case.",
      img_url1: "#{url_prefix}/52.jpg", img_url2: "#{url_prefix}/53.jpg", img_url3: "#{url_prefix}/54.jpg" },
    { title: "Brand New Nexus 5X", description: "Just received this as a warranty replacement from google however I no longer need it. Its literally new just arrived Unlocked Charcoal Grey 16gig",
      img_url1: "#{url_prefix}/55.jpg", img_url2: nil, img_url3: nil },
    { title: "iPhone 6s - SEALED, AT&T, 16gb, Silver/wht", description: "We bought this for someone on the family plan, didn't end up using it. This is the real deal. It is an unopened box, but I will take the sim card out of the phone (once it's purchased) since it's tied to my account. You can use your own sim card.",
      img_url1: "#{url_prefix}/58.jpg", img_url2: "#{url_prefix}/59.jpg", img_url3: "#{url_prefix}/60.jpg" },
    { title: "BUY/SELL/TRADE VIDEO GAMES FREE", description: "Hello! I have been collecting, trading & selling games for over 10 years! I want to give you CASH for your OLD VIDEO games and consoles.",
      img_url1: "#{url_prefix}/61.jpg", img_url2: nil, img_url3: nil },
    { title: "Nintendo Wii Video Game System w/16 Games", description: "2 Controllers 1- Motion Plus Adapter in Silicone Covers 2-Nunchuks AC Adapter Sensor Bar",
      img_url1: "#{url_prefix}/64.jpg", img_url2: "#{url_prefix}/65.jpg", img_url3: "#{url_prefix}/66.jpg" },
    { title: "Various PS2 video games - $5", description: "Various PS2 video games for $5 each.",
      img_url1: "#{url_prefix}/67.jpg", img_url2: nil, img_url3: nil },
    { title: "Conair professional clothes steamer", description: "Professional grade clothes steamer - easier than ironing, and better for high end clothes. Love this thing - moving cross country and can't take it with me.",
      img_url1: "#{url_prefix}/70.jpg", img_url2: "#{url_prefix}/71.jpg", img_url3: nil },
    { title: "Huge Bag of Girl Clothes - size 7 & 8 for just $20", description: "A whole closet full of girl's clothes for just $20! Some items are brand new or only worn once, others are gently used. Everything you see in the photos is included. Size 7 and 8, so will fit a 6-8 year old girl.",
      img_url1: "#{url_prefix}/73.jpg", img_url2: "#{url_prefix}/74.jpg", img_url3: "#{url_prefix}/75.jpg" },
    { title: "Unique petite lady clothes - size 0 - $7", description: "Hi there, Never find anything in the store that fit you? I am size 0 and want to leave my awesome clothes back for you. Plenty of dresses, business casual items.",
      img_url1: "#{url_prefix}/76.jpg", img_url2: "#{url_prefix}/77.jpg", img_url3: "#{url_prefix}/78.jpg" },
    { title: "Baby and kids clothes and toys", description: "Lots of excellent quality baby toys, baby eating items, toddler toys, baby and toddler clothes and shoes (boys); Thomas the train sets...trying to clear out our garage!!! We have a lot more than shown in the photo.",
      img_url1: "#{url_prefix}/79.jpg", img_url2: nil, img_url3: nil },
    { title: "College Student Starter Kitchenware", description: "Lovingly used but functional set of kitchen ware, perfect for filling out a college student's kitchen. Set includes: Rice Cooker Blender 6 Mugs Large Skillet (not pretty, but excellent for omelettes, quesadillas, stirfry, steaks, etc.)",
      img_url1: "#{url_prefix}/82.jpg", img_url2: "#{url_prefix}/83.jpg", img_url3: nil },
    { title: "Crystal Glass Wine Decanter", description: "Hello! I'm looking to sell this glass wine decanter by HiCoup. Item is still in the box and never has been opened. It is 800mL, artisan made, mouth-blown and lead-free crystal glass red wine carafe.",
      img_url1: "#{url_prefix}/85.jpg", img_url2: "#{url_prefix}/86.jpg", img_url3: "#{url_prefix}/87.jpg" }
  ].freeze
end
